FROM ghcr.io/qwenlm/qwen-code:latest
RUN apt-get update && apt-get install -y python3-pip python3-notebook jupyter-nbconvert python3-pandas vim && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN echo "alias python=python3" >> /etc/profile.d/alias.sh
CMD ["qwen"]